services:
  db:
    image: postgres:15-alpine
    container_name: wms_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - wms-postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wms_user
      - POSTGRES_PASSWORD=wms_password
      - POSTGRES_DB=wms_db

volumes:
  wms-postgres_data:
