// @ts-nocheck
"use client";
import React, { useState, useEffect } from "react";
import { Box, Group, Title, Table, TextInput, Loader, Text, Autocomplete, ActionIcon, Tooltip } from "@mantine/core";
import { api, unwrap, fmt, fmtDateTime, saveXlsx } from "../lib/api";
import { IconFileTypePdf, IconFileSpreadsheet, IconSearch, IconFilter, IconRefresh } from "@tabler/icons-react";
import * as XLSX from "xlsx";

function exportExcel(data: any[], from: string, to: string) {
  const dateStr = new Date().toLocaleDateString("id-ID", { day: "2-digit", month: "long", year: "numeric" });
  const periodeStr = from && to ? `${from} s/d ${to}` : from ? `Dari ${from}` : to ? `Sampai ${to}` : "Semua Periode";
  const headerRows = [["LAPORAN RELOKASI"], [`Dicetak: ${dateStr}`], [`Periode: ${periodeStr}`], [], ["ID","Tanggal","Jam","Item / Produk","Batch","Qty","Satuan","Asal (Rak)","Asal Zone","Tujuan (Rak)","Tujuan Zone","Keterangan","Dieksekusi Oleh","Waktu Eksekusi"]];
  const rows = data.map((r:any)=>[ `LOG-${r.id}`, r.created_at? fmt(r.created_at):"-", r.created_at? fmtDateTime(r.created_at).split(" ")[1]:"-", r.barang?.nama||"-", r.batch_no||"-", r.qty, r.satuan||"", r.gudang?.name||"-", r.gudang?.zone||"-", r.gudang_tujuan?.name||"-", r.gudang_tujuan?.zone||"-", r.note||r.keterangan||"-", r.executed_by_username||r.user?.username||"sistem", fmtDateTime(r.executed_at||r.created_at)]);
  const ws = XLSX.utils.aoa_to_sheet([...headerRows,...rows]);
  ws["!merges"]=[{s:{r:0,c:0},e:{r:0,c:13}},{s:{r:1,c:0},e:{r:1,c:13}},{s:{r:2,c:0},e:{r:2,c:13}}];
  ws["!cols"]=[{wch:10},{wch:14},{wch:10},{wch:26},{wch:14},{wch:8},{wch:8},{wch:14},{wch:10},{wch:14},{wch:10},{wch:30},{wch:16},{wch:18}];
  const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,"Relokasi");
  const periodePart = from&&to? `_${from.replace(/-/g,"")}-${to.replace(/-/g,"")}`:`_${new Date().toISOString().split("T")[0].replace(/-/g,"")}`;
  saveXlsx(XLSX,wb,`ReportRelokasi${periodePart}.xlsx`);
}

export default function ReportRelocationPage(){
  const [logs,setLogs]=useState<any[]>([]); const [shifts,setShifts]=useState<any[]>([]); const [search,setSearch]=useState(""); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{ api().get("/shifts").then(r=>setShifts(unwrap(r))); load(); },[]);
  const load=async()=>{ setLoading(true); try{ const p=new URLSearchParams(); if(from) p.set("from",from); if(to) p.set("to",to); const res=await api().get(`/inventory/logs/relocation?${p}`); setLogs(unwrap(res)); }catch(e){console.error(e);} setLoading(false); };
  const filtered=logs.filter((r:any)=>!search|| r.barang?.nama?.toLowerCase().includes(search.toLowerCase())|| r.gudang?.name?.toLowerCase().includes(search.toLowerCase())|| r.gudang_tujuan?.name?.toLowerCase().includes(search.toLowerCase())|| String(r.id).includes(search));
  const handlePrint=()=>{ const periodeStr=from&&to?`${from} s/d ${to}`:from?`Dari ${from}`:to?`Sampai ${to}`:"Semua Periode"; const win=window.open("","_blank"); if(!win) return; win.document.write(`<html><head><title>Laporan Relokasi - ${periodeStr}</title><style>body{font-family:Arial;padding:20px;font-size:10px}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #333;padding:5px;text-align:left}th{background:#1f2937;color:#fff}</style></head><body><div style="font-size:15px;font-weight:bold">LAPORAN RELOKASI</div><div style="border-bottom:2px solid #000;padding-bottom:8px;margin-bottom:12px">Periode: ${periodeStr} | Dicetak: ${new Date().toLocaleDateString("id-ID",{day:"2-digit",month:"long",year:"numeric"})}</div><table><thead><tr><th>ID</th><th>Tanggal</th><th>Item</th><th>Qty</th><th>Asal</th><th>Tujuan</th><th>Keterangan</th><th>Eksekutor</th></tr></thead><tbody>${filtered.map((r:any)=>`<tr><td>LOG-${r.id}</td><td>${fmt(r.created_at)}</td><td>${r.barang?.nama||"-"} (${r.batch_no||"-"})</td><td>${r.qty} ${r.satuan||""}</td><td>${r.gudang?.name||"-"} (${r.gudang?.zone||"-"})</td><td>${r.gudang_tujuan?.name||"-"} (${r.gudang_tujuan?.zone||"-"})</td><td>${r.note||"-"}</td><td>${r.executed_by_username||r.user?.username||"sistem"}<br>${fmtDateTime(r.executed_at||r.created_at)}</td></tr>`).join("")}</tbody></table><script>window.onload=()=>{window.print();window.close()}</script></body></html>`); win.document.close(); };
  return (<Box p="md" bg="#fff" style={{minHeight:"100vh"}}>
    <Group justify="space-between" align="center" mb="lg" wrap="wrap" gap="xs" pb="xs" style={{borderBottom:"1px solid #f1f5f9"}}><Title order={3} style={{color:"#e6921e",fontWeight:900}}>REPORT RELOKASI</Title>
    <Group gap="xs" align="center" wrap="wrap"><TextInput placeholder="Cari item/rak..." size="xs" radius="md" style={{width:160}} leftSection={<IconSearch size={14}/>} value={search} onChange={e=>setSearch(e.target.value)}/><Group gap={4} wrap="nowrap" align="center"><Text size="xs" fw={600} c="dimmed">Dari</Text><TextInput type="date" size="xs" radius="md" value={from} onChange={e=>setFrom(e.target.value)} style={{width:115}}/></Group><Group gap={4} wrap="nowrap" align="center"><Text size="xs" fw={600} c="dimmed">Sampai</Text><TextInput type="date" size="xs" radius="md" value={to} onChange={e=>setTo(e.target.value)} style={{width:115}}/></Group><Tooltip label="Filter"><ActionIcon color="blue" variant="filled" size="md" radius="md" onClick={load}><IconFilter size={16}/></ActionIcon></Tooltip><Tooltip label="Reset"><ActionIcon color="gray" variant="outline" size="md" radius="md" onClick={()=>{setSearch("");setFrom("");setTo("");load();}}><IconRefresh size={16}/></ActionIcon></Tooltip><Tooltip label="Export Excel"><ActionIcon color="teal" variant="filled" size="md" radius="md" onClick={()=>exportExcel(filtered,from,to)}><IconFileSpreadsheet size={16}/></ActionIcon></Tooltip><Tooltip label="Print PDF"><ActionIcon color="red" variant="filled" size="md" radius="md" onClick={handlePrint}><IconFileTypePdf size={16}/></ActionIcon></Tooltip></Group></Group>
    {loading?<Loader color="orange"/>:<Table.ScrollContainer minWidth={1000}><Table withColumnBorders style={{fontSize:11,border:"1px solid #dee2e6"}}><Table.Thead style={{background:"#f0fdfa",borderBottom:"2px solid #99f6e4"}}><Table.Tr><Table.Th style={{color:"#0f766e",textAlign:"center"}}>ID</Table.Th><Table.Th style={{color:"#0f766e"}}>Tanggal / Jam</Table.Th><Table.Th style={{color:"#0f766e"}}>Item</Table.Th><Table.Th style={{color:"#0f766e",textAlign:"center"}}>Qty</Table.Th><Table.Th style={{color:"#0f766e",textAlign:"center"}}>Asal</Table.Th><Table.Th style={{color:"#0f766e",textAlign:"center"}}>Tujuan</Table.Th><Table.Th style={{color:"#0f766e"}}>Keterangan</Table.Th><Table.Th style={{color:"#0f766e",textAlign:"center"}}>Eksekutor</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{filtered.length===0?<Table.Tr><Table.Td colSpan={8} ta="center" c="dimmed">Tidak ada log relokasi</Table.Td></Table.Tr>:filtered.map((r:any)=><Table.Tr key={r.id}><Table.Td ta="center" fw={700}>LOG-{r.id}</Table.Td><Table.Td ta="center"><div>{fmt(r.created_at)}</div><div style={{fontSize:10,color:"#64748b"}}>{fmtDateTime(r.created_at).split(" ")[1]}</div></Table.Td><Table.Td fw={600}>{r.barang?.nama}<div style={{fontSize:10,color:"#64748b"}}>Batch: {r.batch_no||"-"} Exp: {r.expiry_date?fmt(r.expiry_date):"-"}</div></Table.Td><Table.Td ta="center">{r.qty} {r.satuan}</Table.Td><Table.Td ta="center" fw={700}>{r.gudang?.name||"-"}<div style={{fontSize:10,color:"#64748b"}}>Zone {r.gudang?.zone||"-"}</div></Table.Td><Table.Td ta="center" fw={700} c="teal">{r.gudang_tujuan?.name||"-"}<div style={{fontSize:10,color:"#64748b"}}>Zone {r.gudang_tujuan?.zone||"-"}</div></Table.Td><Table.Td>{r.note||r.keterangan||"-"}</Table.Td><Table.Td ta="center"><div>{r.executed_by_username||r.user?.username||"sistem"}</div><div style={{fontSize:10,color:"#64748b"}}>{fmtDateTime(r.executed_at||r.created_at)}</div></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</Box>);
}
