[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
logfile_backups=2
pidfile=/var/run/supervisord.pid
minfds=1024


[program:rm-backend]
command=/app/wrappers/rm-backend.sh
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=10
startretries=5
stdout_logfile=/var/log/rm-backend.log
stderr_logfile=/var/log/rm-backend.log
priority=3

[program:rm-frontend]
command=/app/wrappers/rm-frontend.sh
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=10
startretries=5
stdout_logfile=/var/log/rm-frontend.log
stderr_logfile=/var/log/rm-frontend.log
priority=5
